### PR TITLE
Fix C++17 std::iterator deprecation warning in CodeGenFormat

### PR DESCRIPTION
**Pull request by konstantinschwarz**
Pushing @gbossu's commit to fix build warnings/errors

### CODE REVIEW

**Comment by makslevental** [comment]
Cool. lemme try this in a bit with the release pipeline (which is where I ran into this issue yesterday).

**Comment by stephenneuendorffer** [comment]
FWIW, I think I tried that and didn't see a difference, so I ended up dropping it again.

**Comment by makslevental** [comment]
@konstantinschwarz can you please send this as a branch merge instead of fork merge so that I can commit on top.

**Comment by makslevental** [comment]
closing in favor of https://github.com/Xilinx/llvm-aie/pull/22

**Pull request closed without merging**
